import { AppData } from '../types';

export function getInitialData(): AppData {
  return {
    users: [
      {
        id: 'admin-1',
        username: 'admin',
        password: 'admin123',
        role: 'admin',
        fullName: 'Administrador',
        email: 'admin@club.com',
        active: true,
        createdAt: new Date().toISOString(),
      },
      {
        id: 'user-1',
        username: 'usuario',
        password: 'usuario123',
        role: 'user',
        fullName: 'Usuario Demo',
        email: 'usuario@club.com',
        active: true,
        createdAt: new Date().toISOString(),
      },
    ],
    members: [
      {
        id: 'member-1',
        name: 'Juan Pérez',
        email: 'juan.perez@email.com',
        phone: '+1234567890',
        joinDate: '2024-01-15',
        active: true,
        membershipType: 'Completa',
      },
      {
        id: 'member-2',
        name: 'María García',
        email: 'maria.garcia@email.com',
        phone: '+1234567891',
        joinDate: '2024-02-20',
        active: true,
        membershipType: 'Básica',
      },
      {
        id: 'member-3',
        name: 'Carlos López',
        email: 'carlos.lopez@email.com',
        phone: '+1234567892',
        joinDate: '2024-03-10',
        active: true,
        membershipType: 'Premium',
      },
    ],
    categories: [
      {
        id: 'cat-1',
        name: 'Cuotas de Socios',
        type: 'income',
        description: 'Ingresos por cuotas mensuales',
        active: true,
      },
      {
        id: 'cat-2',
        name: 'Donaciones',
        type: 'income',
        description: 'Donaciones recibidas',
        active: true,
      },
      {
        id: 'cat-3',
        name: 'Eventos',
        type: 'income',
        description: 'Ingresos por eventos organizados',
        active: true,
      },
      {
        id: 'cat-4',
        name: 'Mantenimiento',
        type: 'expense',
        description: 'Gastos de mantenimiento',
        active: true,
      },
      {
        id: 'cat-5',
        name: 'Servicios Públicos',
        type: 'expense',
        description: 'Agua, luz, internet, etc.',
        active: true,
      },
      {
        id: 'cat-6',
        name: 'Suministros',
        type: 'expense',
        description: 'Material de oficina y suministros',
        active: true,
      },
    ],
    transactions: [
      {
        id: 'trans-1',
        type: 'income',
        amount: 150,
        category: 'Cuotas de Socios',
        description: 'Cuota mensual - Juan Pérez',
        date: '2025-10-01',
        createdBy: 'admin',
        memberId: 'member-1',
      },
      {
        id: 'trans-2',
        type: 'income',
        amount: 100,
        category: 'Cuotas de Socios',
        description: 'Cuota mensual - María García',
        date: '2025-10-01',
        createdBy: 'admin',
        memberId: 'member-2',
      },
      {
        id: 'trans-3',
        type: 'expense',
        amount: 75,
        category: 'Servicios Públicos',
        description: 'Pago de electricidad',
        date: '2025-10-05',
        createdBy: 'admin',
      },
      {
        id: 'trans-4',
        type: 'income',
        amount: 200,
        category: 'Donaciones',
        description: 'Donación anónima',
        date: '2025-10-10',
        createdBy: 'admin',
      },
      {
        id: 'trans-5',
        type: 'expense',
        amount: 50,
        category: 'Suministros',
        description: 'Material de oficina',
        date: '2025-10-12',
        createdBy: 'admin',
      },
    ],
    fees: [
      {
        id: 'fee-1',
        memberId: 'member-1',
        amount: 150,
        dueDate: '2025-10-01',
        paidDate: '2025-10-01',
        status: 'paid',
        transactionId: 'trans-1',
      },
      {
        id: 'fee-2',
        memberId: 'member-2',
        amount: 100,
        dueDate: '2025-10-01',
        paidDate: '2025-10-01',
        status: 'paid',
        transactionId: 'trans-2',
      },
      {
        id: 'fee-3',
        memberId: 'member-3',
        amount: 200,
        dueDate: '2025-10-01',
        status: 'pending',
      },
    ],
    systemData: {
      clubName: 'Mi Club',
      taxId: '12345678-9',
      address: 'Calle Principal #123, Ciudad',
      phone: '+1234567890',
      email: 'info@miclub.com',
      currency: 'COP',
      fiscalYear: '2025',
    },
  };
}
