import { AppData } from '../types';

const currentYear = new Date().getFullYear();
const currentMonth = new Date().getMonth() + 1;

const monthNames = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
];

function getMonthDateRange(year: number, month: number) {
  const startDate = new Date(year, month - 1, 1);
  const endDate = new Date(year, month, 0);
  return {
    fechaInicio: startDate.toISOString().split('T')[0],
    fechaFin: endDate.toISOString().split('T')[0]
  };
}

export function getInitialData(): AppData {
  return {
    users: [
      {
        id: 'admin-1',
        username: 'admin',
        password: 'admin123',
        role: 'admin',
        fullName: 'Administrador',
        email: 'admin@club.com',
        active: true,
        createdAt: new Date().toISOString(),
      },
      {
        id: 'user-1',
        username: 'tesorero',
        password: 'tesorero123',
        role: 'tesorero',
        fullName: 'Tesorero Demo',
        email: 'tesorero@club.com',
        active: true,
        createdAt: new Date().toISOString(),
      },
    ],
    members: [
      {
        id: 'member-1',
        name: 'Juan Pérez',
        documento: '12345678',
        tipoDocumento: 'CC',
        email: 'juan.perez@email.com',
        phone: '+1234567890',
        direccion: 'Calle 123 #45-67',
        fechaNacimiento: '1990-05-15',
        joinDate: '2024-01-15',
        membershipType: 'Completa',
        nivelAprendizaje: 'Club',
        estado: 'activo',
        active: true,
      },
      {
        id: 'member-2',
        name: 'María García',
        documento: '87654321',
        tipoDocumento: 'CC',
        email: 'maria.garcia@email.com',
        phone: '+1234567891',
        direccion: 'Carrera 89 #12-34',
        fechaNacimiento: '1988-03-20',
        joinDate: '2024-02-20',
        membershipType: 'Completa',
        nivelAprendizaje: 'Rider School',
        estado: 'activo',
        active: true,
      },
      {
        id: 'member-3',
        name: 'Carlos López',
        documento: '11223344',
        tipoDocumento: 'CC',
        email: 'carlos.lopez@email.com',
        phone: '+1234567892',
        direccion: 'Avenida 56 #78-90',
        fechaNacimiento: '1995-08-10',
        joinDate: '2024-03-10',
        membershipType: 'Media',
        nivelAprendizaje: 'Iniciación',
        estado: 'activo',
        active: true,
      },
    ],
    categories: [
      {
        id: 'cat-1',
        name: 'Cuotas de Socios',
        type: 'income',
        description: 'Ingresos por cuotas mensuales',
        active: true,
      },
      {
        id: 'cat-2',
        name: 'Donaciones',
        type: 'income',
        description: 'Donaciones recibidas',
        active: true,
      },
      {
        id: 'cat-3',
        name: 'Eventos',
        type: 'income',
        description: 'Ingresos por eventos organizados',
        active: true,
      },
      {
        id: 'cat-4',
        name: 'Patrocinios',
        type: 'income',
        description: 'Ingresos por patrocinios',
        active: true,
      },
      {
        id: 'cat-5',
        name: 'Mantenimiento',
        type: 'expense',
        description: 'Gastos de mantenimiento',
        active: true,
      },
      {
        id: 'cat-6',
        name: 'Servicios Públicos',
        type: 'expense',
        description: 'Agua, luz, internet, etc.',
        active: true,
      },
      {
        id: 'cat-7',
        name: 'Suministros',
        type: 'expense',
        description: 'Material de oficina y suministros',
        active: true,
      },
      {
        id: 'cat-8',
        name: 'Equipamiento',
        type: 'expense',
        description: 'Compra de equipamiento deportivo',
        active: true,
      },
      {
        id: 'cat-9',
        name: 'Transporte',
        type: 'expense',
        description: 'Gastos de transporte',
        active: true,
      },
    ],
    transactions: [
      {
        id: 'trans-1',
        type: 'income',
        amount: 150,
        category: 'Cuotas de Socios',
        categoryId: 'cat-1',
        description: 'Cuota mensual - Juan Pérez',
        metodoPago: 'transferencia',
        date: `${currentYear}-${String(currentMonth).padStart(2, '0')}-01`,
        createdBy: 'admin-1',
        memberId: 'member-1',
      },
      {
        id: 'trans-2',
        type: 'income',
        amount: 200,
        category: 'Cuotas de Socios',
        categoryId: 'cat-1',
        description: 'Cuota mensual - María García',
        metodoPago: 'efectivo',
        date: `${currentYear}-${String(currentMonth).padStart(2, '0')}-01`,
        createdBy: 'admin-1',
        memberId: 'member-2',
      },
      {
        id: 'trans-3',
        type: 'expense',
        amount: 75,
        category: 'Servicios Públicos',
        categoryId: 'cat-6',
        description: 'Pago de electricidad',
        metodoPago: 'transferencia',
        date: `${currentYear}-${String(currentMonth).padStart(2, '0')}-05`,
        createdBy: 'admin-1',
      },
      {
        id: 'trans-4',
        type: 'income',
        amount: 200,
        category: 'Donaciones',
        categoryId: 'cat-2',
        description: 'Donación anónima',
        metodoPago: 'efectivo',
        date: `${currentYear}-${String(currentMonth).padStart(2, '0')}-10`,
        createdBy: 'admin-1',
      },
      {
        id: 'trans-5',
        type: 'expense',
        amount: 50,
        category: 'Suministros',
        categoryId: 'cat-7',
        description: 'Material de oficina',
        metodoPago: 'efectivo',
        date: `${currentYear}-${String(currentMonth).padStart(2, '0')}-12`,
        createdBy: 'admin-1',
      },
    ],
    fees: [
      {
        id: 'fee-1',
        memberId: 'member-1',
        amount: 150,
        dueDate: `${currentYear}-${String(currentMonth).padStart(2, '0')}-15`,
        paidDate: `${currentYear}-${String(currentMonth).padStart(2, '0')}-01`,
        status: 'paid',
        transactionId: 'trans-1',
      },
      {
        id: 'fee-2',
        memberId: 'member-2',
        amount: 200,
        dueDate: `${currentYear}-${String(currentMonth).padStart(2, '0')}-15`,
        paidDate: `${currentYear}-${String(currentMonth).padStart(2, '0')}-01`,
        status: 'paid',
        transactionId: 'trans-2',
      },
      {
        id: 'fee-3',
        memberId: 'member-3',
        amount: 100,
        dueDate: `${currentYear}-${String(currentMonth).padStart(2, '0')}-15`,
        status: 'pending',
      },
    ],
    systemData: {
      clubName: 'Mi Club Deportivo',
      taxId: '900.123.456-7',
      address: 'Calle Principal #123, Ciudad',
      phone: '+1234567890',
      email: 'info@miclub.com',
      currency: 'COP',
      fiscalYear: currentYear.toString(),
      diaVencimientoDefault: 15,
      porcentajeMora: 10,
    },
    // New data structures
    periodos: [
      ...Array.from({ length: 12 }, (_, i) => {
        const mes = i + 1;
        const { fechaInicio, fechaFin } = getMonthDateRange(currentYear, mes);
        return {
          id: `periodo-${mes}`,
          anio: currentYear,
          mes,
          nombreMes: monthNames[i],
          fechaInicio,
          fechaFin,
          activo: true,
          cerrado: mes < currentMonth,
        };
      }),
    ],
    configMensualidad: [
      {
        id: 'config-1',
        anio: currentYear,
        valorMensual: 50000,
        fechaVencimientoDefault: 15,
        activo: true,
      },
    ],
    detalleTransacciones: [
      {
        id: 'detalle-1',
        idTransaccion: 'trans-1',
        idSocio: 'member-1',
        monto: 150,
        concepto: 'Mensualidad Enero 2026',
      },
      {
        id: 'detalle-2',
        idTransaccion: 'trans-2',
        idSocio: 'member-2',
        monto: 200,
        concepto: 'Mensualidad Enero 2026',
      },
    ],
    pagosMensuales: [
      {
        id: 'pago-1',
        idSocio: 'member-1',
        idPeriodo: 'periodo-1',
        valor: 50000,
        fechaVencimiento: `${currentYear}-01-15`,
        fechaPago: `${currentYear}-01-01`,
        estado: 'pagado',
        idTransaccion: 'trans-1',
        diasMora: 0,
      },
      {
        id: 'pago-2',
        idSocio: 'member-2',
        idPeriodo: 'periodo-1',
        valor: 50000,
        fechaVencimiento: `${currentYear}-01-15`,
        fechaPago: `${currentYear}-01-01`,
        estado: 'pagado',
        idTransaccion: 'trans-2',
        diasMora: 0,
      },
      {
        id: 'pago-3',
        idSocio: 'member-3',
        idPeriodo: 'periodo-1',
        valor: 50000,
        fechaVencimiento: `${currentYear}-01-15`,
        estado: 'pendiente',
        diasMora: 0,
      },
    ],
    cartera: [
      {
        id: 'cartera-1',
        idSocio: 'member-3',
        idPagoMensual: 'pago-3',
        fecha: `${currentYear}-01-15`,
        concepto: 'Recargo por mora - Mensualidad Enero 2026',
        valor: 5000,
        estado: 'pendiente',
      },
    ],
    asistencia: [
      {
        id: 'asistencia-1',
        idSocio: 'member-1',
        fecha: `${currentYear}-01-20`,
        tipoEntrenamiento: 'Fútbol',
        estado: 'Presente',
        observacion: 'Asistió normalmente',
        registradoBy: 'admin-1',
      },
      {
        id: 'asistencia-2',
        idSocio: 'member-2',
        fecha: `${currentYear}-01-20`,
        tipoEntrenamiento: 'Fútbol',
        estado: 'Presente',
        observacion: 'Asistió normalmente',
        registradoBy: 'admin-1',
      },
      {
        id: 'asistencia-3',
        idSocio: 'member-3',
        fecha: `${currentYear}-01-20`,
        tipoEntrenamiento: 'Fútbol',
        estado: 'Ausente',
        observacion: 'Sin justificación',
        registradoBy: 'admin-1',
      },
    ],
    jerseyOrders: [
      {
        id: 'jersey-1',
        idSocio: 'member-1',
        fecha: `${currentYear}-01-10`,
        tipo: 'Jersey',
        talla: 'M',
        aplica: 'Logo del club',
        valor: 45000,
        estado: 'Entregado',
        fechaEntrega: `${currentYear}-01-15`,
        observaciones: 'Pedido entregado',
      },
      {
        id: 'jersey-2',
        idSocio: 'member-2',
        fecha: `${currentYear}-01-12`,
        tipo: 'Jersey',
        talla: 'S',
        aplica: 'Logo del club + número',
        valor: 55000,
        estado: 'Listo',
        observaciones: 'Listo para entrega',
      },
    ],
    inventarioJersey: [
      {
        id: 'inv-jersey-1',
        idPedido: 'jersey-1',
        nroItem: 1,
        estadoEntrega: 'Entregado',
        fechaEntrega: `${currentYear}-01-15`,
      },
    ],
    lockers: [
      {
        id: 'locker-1',
        idSocio: 'member-1',
        numeroCamerino: 'A-01',
        anio: currentYear,
        valor: 30000,
        fechaAsignacion: `${currentYear}-01-01`,
        fechaPago: `${currentYear}-01-05`,
        estado: 'Pagado',
        idTransaccion: 'trans-1',
      },
      {
        id: 'locker-2',
        idSocio: 'member-2',
        numeroCamerino: 'A-02',
        anio: currentYear,
        valor: 30000,
        fechaAsignacion: `${currentYear}-01-01`,
        estado: 'Asignado',
      },
    ],
    healthPolicies: [
      {
        id: 'poliza-1',
        idSocio: 'member-1',
        tipo: 'Básica',
        numeroPoliza: 'POL-2026-001',
        fechaContratacion: `${currentYear}-01-01`,
        fechaVencimiento: `${currentYear + 1}-01-01`,
        valor: 120000,
        estado: 'Activa',
        observaciones: 'Póliza de salud básica',
      },
    ],
    compras: [
      {
        id: 'compra-1',
        concepto: 'Balones de fútbol',
        tipo: 'Deportivo',
        cantidad: 10,
        valorUnitario: 25000,
        valorTotal: 250000,
        fecha: `${currentYear}-01-05`,
        proveedor: 'Deportes Colombia',
        factura: 'F-001',
        categoriaId: 'cat-8',
        observaciones: 'Compra de balones para entrenamiento',
        createdBy: 'admin-1',
      },
    ],
    facturas: [
      {
        id: 'factura-1',
        fecha: `${currentYear}-01-05`,
        concepto: 'Balones de fútbol',
        valorTotal: 250000,
        proveedor: 'Deportes Colombia',
        nitProveedor: '12345678-9',
        numeroFactura: 'F-001',
        fechaRecepcion: `${currentYear}-01-05`,
        estado: 'Pagada',
        idCompra: 'compra-1',
        createdBy: 'admin-1',
      },
    ],
    detalleFacturas: [
      {
        idFactura: 'factura-1',
        nroLinea: 1,
        servicio: 'Balón de fútbol profesional',
        descripcion: 'Balón marca Adidas modelo FIFA',
        cantidad: 10,
        valorUnitario: 25000,
        valorTotal: 250000,
        iva: 0,
        descuento: 0,
      },
    ],
  };
}
